[build]
  command = "npm run build"
  publish = "dist"
  functions = "lambda"

[context.deploy-preview]
  command = "npm run build-preview"

[[headers]]
  for "/*"
  [headers.values]
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
