baseurl: /
languageCode: en-us
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
googleAnalytics: UA-122953166-1
title: Stable Unit
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
languages:
  en:
    LanguageName: English
    title: >-
      Stable Unit: Decentralized low-volatility cryptocurrency with multi-layer
      stabilization
    weight: 1
    menu:
      main:
        - url: "#mission"
          name: Mission
          weight: 1
        - url: "#stableunit"
          name: What is
          weight: 2
        - url: "#roadmap"
          name: Roadmap
          weight: 3
        - url: "#team"
          name: Team
          weight: 4
        - url: "#contributors"
          name: Contributors
          weight: 5
        - url: "#usecases"
          name: Use cases
          weight: 6
        - url: "#daico"
          name: DAICO
          weight: 7

  ru:
    LanguageName: Русский
    title: >-
      Stable Unit: Децентрализированая криптовалюта с низкой волатильностью и
      мульти-уровневой стабилизацией
    weight: 2
    menu:
      main:
        - url: "#explanation"
          name: Как это работает
          weight: 1
        - url: /team
          name: Команда
          weight: 2
        - url: /roadmap
          name: Стратегия
          weight: 3
